services:

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: chatops-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://chatops:chatops123@postgres:5432/chatops
      KUBECONFIG: /root/.kube/config

    volumes:
      - /home/ubuntu/.kube/config-docker:/root/.kube/config:ro

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://35.181.183.50:8000"

    container_name: chatops-frontend

    environment:
      NEXT_PUBLIC_API_URL: "http://35.181.183.50:8000"

    ports:
      - "3000:3000"

    depends_on:
      - backend
      
  postgres:
    image: postgres:16
    container_name: postgres

    restart: always

    environment:
      POSTGRES_DB: chatops
      POSTGRES_USER: chatops
      POSTGRES_PASSWORD: chatops123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    profiles:
      - monitoring

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    profiles:
      - monitoring

    ports:
      - "9093:9093"

    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    profiles:
      - monitoring

    ports:
      - "3001:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    profiles:
      - monitoring

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    profiles:
      - monitoring

    volumes:
      - /var/log:/var/log

    command: -config.file=/etc/promtail/config.yml

    depends_on:
      - loki

  node-exporter:
    image: prom/node-exporter:latest
    container_name: chatops-node-exporter
    profiles:
      - monitoring

    restart: unless-stopped

    ports:
      - "9100:9100"

volumes:
  postgres_data:
