global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'chatops.alerts@gmail.com'
  smtp_auth_username: 'chatops.alerts@gmail.com'
  smtp_auth_password: 'qgjy syqf ednb bpuq'
  smtp_require_tls: true

route:
  receiver: email-admin

receivers:

- name: email-admin

  email_configs:

  - to: 'evradlan5@gmail.com'

    send_resolved: true

    headers:
      Subject: '[ChatOps AI] Alerte Monitoring'
