name: Deploy ChatOps Project

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Copy files to EC2
    uses: appleboy/scp-action@master
    with:
      host: ${{ secrets.HOST }}
      username: ubuntu
      key: ${{ secrets.SSH_KEY }}
      source: "."
      target: "/home/ubuntu/chatops"

  - name: Execute remote commands
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.HOST }}
      username: ubuntu
      key: ${{ secrets.SSH_KEY }}
      script: |
        cd /home/ubuntu/chatops
        docker compose down
        docker system prune -af
        docker compose up -d --build
```
