name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SCP files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "15.237.255.117"
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/ubuntu/chatops"

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "15.237.255.117"
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/chatops
            docker compose down
            docker compose up -d --build
